### ISSUE TITLE
Error building demo project

### ISSUE THREAD

**Issue by dmitry-yudakov** [OLIMEX/LoRa-STM32WL-DevKIT#1]
I'm trying to build [SOFTWARE/BB-STM32WLE-WAN](https://github.com/OLIMEX/LoRa-STM32WL-DevKIT/tree/main/SOFTWARE/BB-STM32WLE-WAN) project with CubeIDE but it gives me error about missing `iis2mdc/iis2mdc_reg.h`

```
make -j7 all 
arm-none-eabi-gcc "../Core/Src/main.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../Core/Inc -I../Utilities/trace/adv_trace -I../Drivers/STM32WLxx_HAL_Driver/Inc -I../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../Utilities/misc -I../Utilities/sequencer -I../Utilities/timer -I../Utilities/lpm/tiny_lpm -I../Middlewares/Third_Party/SubGHz_Phy -I../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../Drivers/CMSIS/Include -I../LoRaWAN/App -I../LoRaWAN/Target -I../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../Middlewares/Third_Party/LoRaWAN/Crypto -I../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../Middlewares/Third_Party/LoRaWAN/Mac -I../Middlewares/Third_Party/LoRaWAN/LmHandler -I../Middlewares/Third_Party/LoRaWAN/Utilities -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"Core/Src/main.o"  -mfloat-abi=soft -mthumb -o "Core/Src/main.o"

../Core/Src/main.c:29:10: fatal error: iis2mdc/iis2mdc_reg.h: No such file or directory
   29 | #include "iis2mdc/iis2mdc_reg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It seems `iis2mdc` in [SOFTWARE/BB-STM32WLE-WAN/Core/Src](https://github.com/OLIMEX/LoRa-STM32WL-DevKIT/tree/main/SOFTWARE/BB-STM32WLE-WAN/Core/Src) might be a symbolic link or something but in my cloned project it's just an empty directory.

I thought it might be a git submodule but I cannot find `.gitmodules` file anywhere.

Should I somehow import this library?

I tried cloning couple of projects like [this](https://github.com/STMicroelectronics/STM32CubeU5) or [this](https://github.com/stm32duino/IIS2MDC) and use them in place of `iis2mdc` but it results in other errors and feels like a wrong direction.

Thank you in advance.

**Comment by DanKoloff** [comment]
Exactly it seems like it is some link instead of real deal. I think the original folder had .git inside and got ignored. Try with these two in the archive:

[iis2mdc.zip](https://github.com/OLIMEX/LoRa-STM32WL-DevKIT/files/7979143/iis2mdc.zip)

**Comment by dmitry-yudakov** [comment]
Yep, it builds with these files. Thank you!

I'll prepare a PR.

**Comment by DanKoloff** [comment]
Thank you for the report and testing. I will upload the missing files to the repo later. Cheers!
